/**
 * O léxico das MENÇÕES — os nomes próprios que o `annotateText` reconhece
 * dentro de um parágrafo de resumo ou de estudo. Client-safe: o anotador roda
 * no render, e o `SummaryView` é `"use client"`.
 *
 * Três decisões governam estas listas:
 *
 * 1. **O casamento é EXATO — acentos e maiúscula inclusive.** É o que separa
 *    "Jó" de "jó", "Roma" de "roma" e "Marcos" (o evangelista) de "marcos"
 *    (as balizas). Um casamento tolerante a acento, como o do gate do pipeline
 *    ao vivo (`lib/bible/detect.ts`), existe porque LÁ a entrada é transcrição
 *    de fala, cheia de erro; aqui a entrada é texto escrito por um modelo, com
 *    ortografia correta. Tolerância que não é necessária só compra falso
 *    positivo.
 *
 * 2. **Jesus, Cristo, Deus, Senhor e Espírito Santo estão DE FORA, de
 *    propósito.** Eles são o sujeito de quase toda frase de um sermão: marcá-los
 *    pintaria o parágrafo inteiro e destruiria justamente o contraste que a
 *    marcação existe para criar. A regra prática: entra no léxico o nome que
 *    aparece ALGUMAS vezes num texto, nunca o que aparece em toda linha.
 *
 * 3. **A lista é curada, não exaustiva.** Ela cobre quem de fato aparece em
 *    pregação, não os 3.400 nomes próprios da Bíblia. Um nome que falta é uma
 *    palavra sem marcação — invisível. Um nome errado é uma marcação errada no
 *    meio do texto, que o leitor vê. O custo dos dois lados não é o mesmo.
 *
 * Os nomes de FIGURAS CITADAS repetem parte do índice de
 * `lib/prompts/theologians.ts`, e a repetição é consciente: aquele índice é
 * `server-only` e carrega obra, século e tema para MONTAR o prompt; este aqui é
 * uma lista de strings para RECONHECER no texto pronto, e inclui gente que
 * nunca entraria naquele índice (filósofos, historiadores). Ao acrescentar um
 * teólogo lá, considere acrescentá-lo aqui também.
 */

/** Personagens bíblicos. */
export const BIBLE_PEOPLE = [
  // Pentateuco
  "Adão",
  "Eva",
  "Caim",
  "Abel",
  "Enoque",
  "Matusalém",
  "Noé",
  // "Sete" e "Sem" (os filhos) ficaram DE FORA: em início de frase eles são
  // indistinguíveis do numeral e da preposição — "Sete pessoas…", "Sem ele…".
  // Um nome que falta é invisível; um falso positivo é uma marcação errada no
  // meio do parágrafo.
  "Cam",
  "Jafé",
  "Abraão",
  "Abrão",
  "Sara",
  "Sarai",
  "Ló",
  "Hagar",
  "Ismael",
  "Isaque",
  "Rebeca",
  "Esaú",
  "Jacó",
  "Labão",
  "Lia",
  "Raquel",
  "José",
  "Benjamim",
  "Judá",
  "Levi",
  "Rúben",
  "Simeão",
  "Manassés",
  "Efraim",
  "Moisés",
  "Arão",
  "Miriã",
  "Zípora",
  "Jetro",
  "Faraó",
  "Balaão",
  "Coré",
  "Josué",
  "Calebe",
  "Melquisedeque",
  // Históricos
  "Raabe",
  "Débora",
  "Baraque",
  "Gideão",
  "Jefté",
  "Sansão",
  "Dalila",
  "Rute",
  "Noemi",
  "Boaz",
  "Ana",
  "Samuel",
  "Eli",
  "Saul",
  "Davi",
  "Jônatas",
  "Golias",
  "Bate-Seba",
  "Absalão",
  "Natã",
  "Salomão",
  "Roboão",
  "Jeroboão",
  "Acabe",
  "Jezabel",
  "Elias",
  "Eliseu",
  "Naamã",
  "Ezequias",
  "Josias",
  "Zorobabel",
  "Esdras",
  "Neemias",
  "Ester",
  "Mardoqueu",
  "Assuero",
  // Poéticos e proféticos
  "Jó",
  "Isaías",
  "Jeremias",
  "Baruque",
  "Ezequiel",
  "Daniel",
  "Sadraque",
  "Mesaque",
  "Abede-Nego",
  "Nabucodonosor",
  "Belsazar",
  "Dario",
  "Oseias",
  "Gômer",
  "Joel",
  "Amós",
  "Obadias",
  "Jonas",
  "Miqueias",
  "Naum",
  "Habacuque",
  "Sofonias",
  "Ageu",
  "Zacarias",
  "Malaquias",
  // Novo Testamento
  "Maria",
  "Isabel",
  "João Batista",
  "Herodes",
  "Pôncio Pilatos",
  "Pilatos",
  "Caifás",
  "Nicodemos",
  "Simão Pedro",
  "Pedro",
  "André",
  "Tiago",
  "João",
  "Filipe",
  "Bartolomeu",
  "Natanael",
  "Mateus",
  "Tomé",
  "Judas Iscariotes",
  "Judas",
  "Matias",
  "Estêvão",
  "Saulo de Tarso",
  "Saulo",
  "Paulo",
  "Barnabé",
  "Silas",
  "Timóteo",
  "Tito",
  "Lucas",
  "Marcos",
  "Apolo",
  "Áquila",
  "Priscila",
  "Lídia",
  "Cornélio",
  "Ananias",
  "Safira",
  "Gamaliel",
  "Lázaro",
  "Marta",
  "Maria Madalena",
  "Zaqueu",
  "Bartimeu",
  "Onésimo",
  "Filemom",
  "Febe",
  "Demas",
];

/** Lugares bíblicos — cidades, regiões, montes e rios. */
export const BIBLE_PLACES = [
  "Éden",
  "Ur dos Caldeus",
  "Harã",
  "Canaã",
  "Sodoma",
  "Gomorra",
  "Egito",
  "Gósen",
  "Mar Vermelho",
  "Sinai",
  "Horebe",
  "Cades-Barneia",
  "Moabe",
  "Edom",
  "Jordão",
  "Jericó",
  "Siló",
  "Betel",
  "Berseba",
  "Hebrom",
  "Jerusalém",
  "Sião",
  "Samaria",
  "Judeia",
  "Galileia",
  "Nazaré",
  "Belém",
  "Cafarnaum",
  "Betânia",
  "Betsaida",
  "Caná",
  "Mar da Galileia",
  "Monte das Oliveiras",
  "Getsêmani",
  "Gólgota",
  "Calvário",
  "Emaús",
  "Jope",
  "Cesareia",
  "Damasco",
  "Antioquia",
  "Tarso",
  "Chipre",
  "Icônio",
  "Listra",
  "Derbe",
  "Filipos",
  "Tessalônica",
  "Bereia",
  "Atenas",
  "Corinto",
  "Éfeso",
  "Colossos",
  "Mileto",
  "Malta",
  "Roma",
  "Babilônia",
  "Nínive",
  "Assíria",
  "Pérsia",
  "Tiro",
  "Sidom",
  "Patmos",
  "Macedônia",
  "Acaia",
  "Galácia",
  "Israel",
];

/**
 * Gente citada NO texto — teólogos, reformadores, pastores, filósofos. É a
 * categoria de "citações" do produto: quem é trazido para dentro do argumento,
 * mas não faz parte da narrativa bíblica.
 *
 * Sobrenome sozinho entra ao lado do nome completo ("Martinho Lutero" e
 * "Lutero") porque o texto alterna entre os dois. A ordenação por comprimento,
 * feita no anotador, garante que o nome completo vença.
 */
export const CITED_FIGURES = [
  // Igreja antiga e medieval
  "Agostinho de Hipona",
  "Agostinho",
  "Atanásio",
  "Irineu de Lião",
  "Irineu",
  "Orígenes",
  "Tertuliano",
  "João Crisóstomo",
  "Crisóstomo",
  "Jerônimo",
  "Basílio de Cesareia",
  "Gregório de Nissa",
  "Anselmo de Cantuária",
  "Anselmo",
  "Bernardo de Claraval",
  "Tomás de Aquino",
  "Aquino",
  // Reforma
  "Martinho Lutero",
  "Lutero",
  "João Calvino",
  "Calvino",
  "Ulrico Zuínglio",
  "Zuínglio",
  "Filipe Melanchthon",
  "Melanchthon",
  "John Knox",
  "Thomas Cranmer",
  // Puritanos e avivamento
  "John Owen",
  "Richard Baxter",
  "Thomas Watson",
  "John Bunyan",
  "Bunyan",
  "Jonathan Edwards",
  "George Whitefield",
  "Whitefield",
  "John Wesley",
  "Wesley",
  "Charles Spurgeon",
  "Spurgeon",
  // Moderno e contemporâneo
  "Charles Hodge",
  "Abraham Kuyper",
  "Kuyper",
  "Herman Bavinck",
  "Bavinck",
  "B. B. Warfield",
  "Warfield",
  "Karl Barth",
  "Dietrich Bonhoeffer",
  "Bonhoeffer",
  "C. S. Lewis",
  "Francis Schaeffer",
  "Schaeffer",
  "J. I. Packer",
  "Packer",
  "John Stott",
  "Stott",
  "Martyn Lloyd-Jones",
  "Lloyd-Jones",
  "R. C. Sproul",
  "Sproul",
  "John Piper",
  "Timothy Keller",
  "Tim Keller",
  "Keller",
  "D. A. Carson",
  "N. T. Wright",
  "Eugene Peterson",
  // Filosofia e letras que a pregação costuma citar
  "Blaise Pascal",
  "Pascal",
  "Søren Kierkegaard",
  "Kierkegaard",
  "G. K. Chesterton",
  "Chesterton",
  "Fiódor Dostoiévski",
  "Dostoiévski",
];
